#!/bin/sh
#
# Start mdev....
#

case "$1" in
  start)
	echo "Starting mdev..."
	mount -t tmpfs tmpfs /dev  -o size=64k,mode=0755

	mkdir /dev/pts /dev/shm

	#mount -t devpts devpts /dev/pts

	echo "/sbin/mdev" >/proc/sys/kernel/hotplug
	#Make i2c node required for detecting lfp100
	mknod -m 666 /dev/i2c-0 c 89 0

	#Make nodes that mdev does not auto-detect
	mknod -m 666 /dev/gpio c 246 0

	#Mount sysfs and pts
	mount -a

	#Scan hw and create dev nodes
	mdev -s
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
