#!/bin/sh
# Start the LF Daemon, required for alsa, backlight, etc
# is from <lf sources/packages/

case "$1" in
	start)
		start-stop-daemon --start --background --exec /usr/bin/lfd
		;;

	stop)
		start-stop-daemon --stop --name lfd
		;;

	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
